name: Build PDF
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Fonts
        run: |
          sudo apt-get install -y fonts-liberation
          sudo apt-get install -y fonts-cmu
      - name: Install & Update TexLive
        shell: bash -l {0}
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y     \
            texlive-latex-recommended \
            texlive-latex-extra       \
            texlive-fonts-recommended \
            texlive-fonts-extra       \
            texlive-xetex             \
            latexmk                   \
            xindy
      - name: Build QuantEcon Mini Example
        shell: bash -l {0}
        run: |
          jb build mini_book/ --builder pdflatex
      - uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: mini_book/_build/latex/book.pdf
